import type { Metadata } from "next";
import './layout.css';
import Link from "next/link";
import Image from 'next/image';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <div className="header">
          <Image src="/logo.png" width={50} height={50} alt="Logo" />
          <span id="company-name">CAPIBARIBETI</span>
          <div className="tabs">
            <Link className="tab" href="/">Início</Link>
            <Link className="tab" href="/about">Sobre</Link>
            <Link className="tab" href="services">Serviços</Link>
            <Link className="tab" href="/contact">Contato</Link>
          </div>
        </div>
        <div className="main-content">
          {children}
        </div>
        <div className="footer"></div>
      </body>
    </html>
  );
}
